composer.json
=> Adding CSV Importer

modules/wri_external_pub/css/wri_external_pub.css, modules/wri_external_pub/src/Plugin/Block/ExternalPubBlock.php, modules/wri_external_pub/templates/block--wri-external-pub-block.html.twig, modules/wri_external_pub/templates/wri-external-pub-person-block.html.twig, modules/wri_external_pub/wri_external_pub.info.yml, modules/wri_external_pub/wri_external_pub.libraries.yml, modules/wri_external_pub/wri_external_pub.module, modules/wri_publication/components/wri_publication_columns.sfc, modules/wri_services_reader/install/rest.resource.wri_reader_retrieve_node.yml, modules/wri_services_reader/install/user.role.anonymous.yml, modules/wri_services_reader/install/views.view.api_reader_index.yml, modules/wri_services_reader/src/Plugin/rest/resource/WriReaderRetrieveNodeResource.php, modules/wri_services_reader/wri_services_reader.info.yml, modules/wri_services_reader/wri_services_reader.install, modules/wri_services_reader/wri_services_reader.module
=> WRI-1290, WRI-1280, and WRI-1277

modules/wri_publication/components/wri_publication_columns.sfc
=> Adding missing work for WRI-1290

composer.json
Please review thoroughly.
Adding "enclosure" to views RSS feeds.
Issue Number: 2511878
https://www.drupal.org/project/drupal/issues/2511878
Views RSS feeds can display "enclosure" property.
-
-
-
=> WRI-1304 patch views in core to allow RSS enclosure

modules/wri_engagement/js/modal-cookie.js, modules/wri_engagement/templates/download-modal.html.twig, themes/custom/ts_wrin/sass/components/_popup_modal.scss
User clicks the download button, a list of files appears.
Issue Number: WRI-1314
User clicks the download button, a form appears to register to pardot, after completing the form or skipping it the user sees a list of files to download and receives an email from pardot.
-
-
-
=> WRI-1314 Pardot registration before file download list

modules/wri_engagement/js/modal-cookie.js, modules/wri_engagement/templates/download-modal.html.twig, themes/custom/ts_wrin/sass/components/_popup_modal.scss
=> Reverting WRI-1314 and saving the work for later

modules/wri_seo/js/wri_seo.js
=> WRI-1336 fix seo JS errors

modules/wri_services_reader/src/Plugin/rest/resource/WriReaderRetrieveNodeResource.php
=> WRI-1280 replace in api from node type to field_type taxonomy reference

composer.json
If you run a `composer install` on this project you get a list of failed patches. They're failed because the modules associated with them have, in general, included the patches as fixed.
- Updates the core patch for https://www.drupal.org/node/672606
- Removes merged patches for Facets https://www.drupal.org/project/facets/issues/3199156
- Removes merged patch for Field Tools https://www.drupal.org/node/3160564
- Removes merged patch for Schema Metatag https://www.drupal.org/node/3174103
=> updating patches that don't apply. Removing fixed patches.

modules/wri_event/config/install/views.view.events.yml, modules/wri_event/wri_event.install, modules/wri_event/wri_event.module
Issue Number: wri/WRIN#311 
- Updates the event order using a hook to alter the sort on the view.
- Adds a comment to the view so future folks can find this alter query
- See https://github.com/wri/wriflagship/pull/595 for testing instructions and a multidev to test on.
Related PR on the flagship is https://github.com/wri/wriflagship/pull/595
=> Past event sort

wri_sites.install
Visiting `/admin/structure/types/manage/program_center/display/full/layout` causes a fatal error.
- Visiting `/admin/structure/types/manage/program_center/display/full/layout` should load the program page successfully.
- TADA: https://pr-25-wri-china.pantheonsite.io/admin/structure/types/manage/program_center/display/full/layout
Related PR on china: https://github.com/wri/wri-china/pull/25
=> Updating program blocks

modules/wri_language_select/components/wri_language_select.sfc, modules/wri_language_select/config/install/block.block.languageswitcher.yml, modules/wri_language_select/wri_language_select.info.yml, themes/custom/ts_wrin/templates/blocks/block--languageswitcher.html.twig, themes/custom/ts_wrin/templates/layout/page.html.twig
This goes along with the walkthrough we did today detailing how to add a new icon to the header.
- Adds a new module "wri_language_select"
- In that module, adds the sfc file to create the language picker svg and logic
- Demonstrates the changes you'd need to make to the theme in order to add an icon to the page
- Demonstrates the changes you'd need to make to a block to make it show up nicely in the tray.
This module is not enabled by default, so it should not affect the wriflagship site at all.
=> Adds the language switcher to the tray

modules/wri_block/src/Plugin/Block/AddressBlock.php
Currently if you try to update the contents of the Address in the footer, the value of the textarea is "Array". This fixes that.
- Update the footer block. Verify its value can be changed successfully.
Multidev is being created for review in https://github.com/wri/wri-china/pull/28
=> Fixing the address Array.

themes/custom/ts_wrin/config/install/ts_wrin.settings.yml, themes/custom/ts_wrin/templates/blocks/block--ts-wrin-branding.html.twig, themes/custom/ts_wrin/theme-settings.php, themes/custom/ts_wrin/ts_wrin.theme, wri_sites.install
Right now, the site logos are hard coded in the `block--ts-wrin-branding.html.twig` template. That breaks the ability to upload a new logo for IO sites.
What's more, you can't upload svgs as logos right now.
And there's no way of indicating a dark and light version of the logo, which is needed for full-bleed image backgrounds.
- Adds new theme settings for "white_logo"
- Updates the `block--ts-wrin-branding.html.twig` template to use the white_logo and the default site_logo.
- Alters the validation function on the logo fields so you can upload an svg.
- You can try this out by visiting `/admin/appearance/settings/ts_wrin` and changing the uploaded file.
We should test this out …
=> Logo development

modules/wri_taxonomy/wri_taxonomy.module
Issue Number: https://github.com/wri/WRIN/issues/327#issuecomment-973277792
- Adds the translation string to terms with landing pages
- Adds the translation string to terms that drop you on the /resources page
Multidev for China: https://pr-62-wri-china.pantheonsite.io/en/resources and https://pr-62-wri-china.pantheonsite.io/resources
Multidev for flagship: https://pr-629-wriflagship.pantheonsite.io/resources
=> Issue 327 translations2

themes/custom/ts_wrin/js/components/ts_header_nav.js, themes/custom/ts_wrin/package-lock.json, themes/custom/ts_wrin/sass/global/_footer.scss, themes/custom/ts_wrin/sass/global/_header.scss, themes/custom/ts_wrin/sass/global/_ts-hamburger-menu.scss, themes/custom/ts_wrin/templates/layout/region--hamburger-nav.html.twig, themes/custom/ts_wrin/templates/navigation/menu.html.twig
From https://docs.google.com/document/d/1hhnpdMrO5kOG0_p1h6YzuNVZIt7q9p_8BxyBy-SjC9k/edit# -- we built the menus in the hamburger and footer to be pretty flagship specific. This PR makes those menus more likely to work with a variety of submenu types.
- Genericizes the button color behavior in Quick links -- the css assumed that the button would always be the last link in the Quick Links, but it should rely on the "button" class being added to the link.
- Works on the mobile hamburger menu, genericising the contents instead of relying on a specific menu id.
- Updates the flex display of the hamburger Mega menu to align left instead of fill the space
- Updates …
=> Menu styling fixes

themes/custom/ts_wrin/js/components/ts_external_links.js
This adds javascript to open all local file links in a new tab. 
Issue Number: https://github.com/wri/wri-china/issues/121 
Any link to a local file "sites/default/files" will open in a new tab.
=> All file links that are not images open in new tab - #121

themes/custom/ts_wrin/ts_wrin.libraries.yml
=> changed typekit id

github/pull_request_template.md
- Changes out the default PR template for this site to be something we can really use
N/A - this change should not affect upstream sites.
=> Updating the PR template to be more helpful for our purposes.

composer.json, themes/custom/ts_wrin/js/components/wri_more_on.js, themes/custom/ts_wrin/js/main.js, themes/custom/ts_wrin/sass/components/_article-detail.scss
=> 322 more on mobile

composer.json
Flagship PR: https://github.com/wri/wriflagship/pull/683
=> 185 sendgrid

themes/custom/ts_wrin/package-lock.json, themes/custom/ts_wrin/package.json, themes/custom/ts_wrin/sass/ckeditor.scss, themes/custom/ts_wrin/sass/style.scss, themes/custom/ts_wrin/webpack.config.js
=> Using node 16.

themes/custom/ts_wrin/sass/global/_header.scss, themes/custom/ts_wrin/templates/ts_custom/maintenance-page.html.twig
https://github.com/wri/wrin/issues/338
Default maintenance page is busted: 
Issue Number: https://github.com/wri/wrin/issues/338
New maintenance page is simple, clean: 
This should be deployed prior to the D9 upgrade so any site downtime looks professional.
=> #338: add basic maintenance page

README.md
=> The correct url of the starter kit.

composer.json
For Brasil (and other sites) fixes the warning about htmlspecialcharacters that's coming from simple_popup_blocks.
=> Fixing warning about htmlspecialcharacters.

composer.json, themes/custom/ts_wrin/ts_wrin.theme
- Updates padding for the template on 404 pages.
=> 288 404 template fix

themes/custom/ts_wrin/sass/components/_events.scss
https://github.com/wri/wri_sites/issues/53
Date/time on Events all smushed up.
Issue Number: https://github.com/wri/wri_sites/issues/53
- Pleasing amount of whitespace for readability
=> #53 Fix event date/time spacing

modules/wri_person/config/install/core.entity_form_display.paragraph.person_listing.default.yml
Quick fix to the form display of the Person Listing paragraph field.
=> Updating the form mode for a person listing.

modules/wri_31block/config/install/views.view.3_1.yml, modules/wri_featured_tweet/config/install/views.view.featured_tweet.yml, modules/wri_happening_now/config/install/views.view.happening_now.yml, modules/wri_io_content/config/install/core.entity_form_display.node.international_office.default.yml, modules/wri_io_content/config/install/field.field.node.international_office.field_show_more_link.yml, modules/wri_io_content/config/install/field.storage.node.field_show_more_link.yml, modules/wri_io_content/wri_io_content.install, modules/wri_listing_block/config/install/views.view.content_listing.yml, modules/wri_listing_block/config/install/views.view.content_listing_a_to_z.yml, modules/wri_node/config/install/field.storage.node.field_show_more_link.yml, modules/wri_program/config/install/core.entity_form_display.node.program_center.default.yml, modules/wri_program/config/install/field.field.node.program_center.field_show_more_link.yml, modules/wri_program/wri_program.install, modules/wri_project/config/install/core.entity_form_display.node.project_detail.default.yml, modules/wri_project/config/install/field.field.node.project_detail.field_show_more_link.yml, modules/wri_project/config/install/views.view.homepage_projects.yml, modules/wri_project/config/install/views.view.related_to_this_project.yml, modules/wri_project/wri_project.install, modules/wri_publication/config/install/views.view.other_publications_in_this_series.yml, modules/wri_superfeatured/config/install/views.view.superfeatured_content.yml, modules/wri_trending_topics/config/install/views.view.trending_topics.yml, themes/custom/ts_wrin/templates/fields/field--node--field-featured-experts--program-center.html.twig, themes/custom/ts_wrin/templates/fields/field--node--field-featured-experts--project-detail.html.twig, themes/custom/ts_wrin/templates/fields/field--node--field-featured-experts.html.twig, themes/custom/ts_wrin/ts_wrin.theme
https://github.com/wri/wri-china/issues/142
Multidev: https://github.com/wri/wri-china/pull/180
Issue Number: https://github.com/wri/wri-china/issues/142
- Adds Add the 'Show More Link' field to the International Office, Program, and Project content types via `drush updb`
=> 142 optional view all

modules/wri_author/src/Plugin/Field/FieldFormatter/ListOfAuthors.php
- Adds "and" to translated strings for #92 
-
-
=> Adds and to translated strings - #92

themes/custom/ts_wrin/sass/components/_search-archive.scss
=> Issue #838 fixing z-index problem.

modules/wri_language_select/components/wri_language_select.sfc, modules/wri_publication/config/install/core.entity_view_display.node.publication.main_content.yml, modules/wri_search/components/wri_search_button.sfc, modules/wri_search/components/wri_search_menu.sfc, themes/custom/ts_wrin/sass/components/_detail-meta.scss, themes/custom/ts_wrin/sass/config/_04.base.scss, themes/custom/ts_wrin/templates/blocks/block--languageswitcher.html.twig, themes/custom/ts_wrin/templates/layout/region--hamburger-nav.html.twig, themes/custom/ts_wrin/templates/ts_custom/ts-hamburger-nav.html.twig
Finds a variety of untranslatable strings and either removes or updates them to be trasnlatable.
=> Translations

modules/wri_event/config/install/core.entity_view_display.node.event.card.yml, modules/wri_event/config/install/core.entity_view_display.node.event.large_image_teaser.yml, modules/wri_event/config/install/core.entity_view_display.node.event.teaser.yml
=> Issue #381 updating dates on events.

composer.json
- Adds the custom_robots module, but does not enable it.
=> Issue #104 adding this package.

modules/wri_31block/config/install/views.view.3_1.yml, modules/wri_author/config/install/views.view.authored_by.yml, modules/wri_engagement/config/install/field.field.block_content.modal.field_webform.yml, modules/wri_featured_tweet/config/install/views.view.featured_tweet.yml, modules/wri_featured_tweet/config/install/views.view.featured_tweets_entity_browser.yml, modules/wri_happening_now/config/install/views.view.happening_now.yml, modules/wri_io_content/config/install/views.view.countries.yml, modules/wri_listing_block/config/install/views.view.content_listing.yml, modules/wri_listing_block/config/install/views.view.content_listing_a_to_z.yml, modules/wri_media/config/install/views.view.files_browser.yml, modules/wri_node/config/install/views.view.content_by_type.yml, modules/wri_person/config/install/views.view.orderable_people.yml, modules/wri_person/config/install/views.view.people_at_this_io.yml, modules/wri_program/config/install/views.view.all_topics.yml, modules/wri_program/config/install/views.view.programs_centers.yml, modules/wri_project/config/install/views.view.featured_experts.yml, modules/wri_project/config/install/views.view.homepage_projects.yml, modules/wri_project/config/install/views.view.related_to_this_project.yml, modules/wri_publication/config/install/views.view.other_publications_in_this_series.yml, modules/wri_search/config/install/views.view.events.yml, modules/wri_search/config/install/views.view.experts_staff.yml, modules/wri_search/config/install/views.view.project_experts.yml, modules/wri_search/config/install/views.view.related_content.yml, modules/wri_search/config/install/views.view.resources.yml, modules/wri_search/config/install/views.view.search.yml, modules/wri_services_reader/install/views.view.api_reader_index.yml, modules/wri_superfeatured/config/install/views.view.superfeatured_content.yml, modules/wri_taxonomy/config/install/views.view.resource_types.yml, modules/wri_taxonomy/config/install/views.view.tagged_with.yml, modules/wri_trending_topics/config/install/views.view.trending_topics.yml
I had forgotten that some views are referenced by uuid on fields, and removed those uuids thinking they were a mistake.
=> Indonesia install fixes

modules/wri_common/src/Plugin/Field/FieldFormatter/TokenizedLinkFieldFormatter.php
- Checks to make sure you're not attaching an external url for the More link on 3 + 1 blocks, etc.
=> Issue #343 problem where an external link caused a WSOD.

modules/wri_author/config/install/views.view.authors.yml, modules/wri_author/src/Commands/WriAuthorCustomCommands.php, modules/wri_author/wri_author.install, modules/wri_author/wri_author.services.yml
=> Issue 212 authors2

themes/custom/ts_wrin/sass/components/_search-results.scss
=> Issue #297 fixing search padding.

.circleci/config.yml
=> Removing the ssh key step, I don't think we need that.

composer.json, modules/wri_common/src/Plugin/views/argument/StringWithSpaceArgument.php, modules/wri_common/wri_common.module, modules/wri_taxonomy/config/install/views.view.resource_types.yml, modules/wri_taxonomy/wri_taxonomy.info.yml, modules/wri_taxonomy/wri_taxonomy.install
…atch for hypens should still be in here, to deal with spaces.
- Swapping out a patch that's closed with one that we do still need.
=> #142 Adds new view handler  for taxonomy arguments with spaces.

.gitignore, composer.json, modules/wri_node/config/install/field.storage.node.field_staff_group.yml, modules/wri_person/config/install/core.entity_form_display.node.person.default.yml, modules/wri_person/config/install/field.field.node.person.field_staff_group.yml, modules/wri_person/config/install/language.content_settings.taxonomy_term.staff_groups.yml, modules/wri_person/wri_person.install, modules/wri_person/wri_person.post_update.php, modules/wri_search/config/install/search_api.index.sitewide.yml, modules/wri_search/config/install/views.view.experts_staff.yml, modules/wri_taxonomy/config/install/taxonomy.vocabulary.staff_groups.yml
- Adds a grouping  taxonomy to Person content types and sorts by those on the experts page.
- Creates update hooks to set the values for the different people types.
=> 379 groups

composer.json
=> New patchs

modules/wri_article/templates/wri-article-columns.html.twig, modules/wri_node/config/install/field.storage.node.field_publication_series.yml, modules/wri_publication/config/install/views.view.other_publications_in_this_series.yml, modules/wri_publication/wri_publication.install, themes/custom/ts_wrin/js/components/wri_more_on.js, themes/custom/ts_wrin/sass/components/_article-detail.scss, themes/custom/ts_wrin/sass/components/_more-on.scss, themes/custom/ts_wrin/sass/components/_publication-detail.scss, themes/custom/ts_wrin/sass/style.scss, themes/custom/ts_wrin/templates/fields/viewfield--node--field-in-this-series.html.twig
- Makes the "In this Series" view allow for multiple values from the Node's Publication Series field.
=> Issue 106 multiple series

composer.json
=> Trying out this patch.

modules/wri_search/config/schema/wri_search.schema.yml, modules/wri_search/src/Plugin/Block/WrinSearchBlock.php, modules/wri_search/templates/wri-search-menu.html.twig, modules/wri_search/wri_search.module
- Updates the  /search url for the menu form to go to a url based on the language you're in.
=> Issue #335 making the search form destination translatable.

themes/custom/ts_wrin/templates/layout/html.html.twig
=> added Google Consent Mode script

modules/wri_search/config/install/views.view.experts_staff.yml, modules/wri_search/wri_search.install
- Adds a relvancy sort, and makes  the Full Text require all words be present instead of that some of the words be present
- Adds an update hook to update existing IOs
- Rearranges the config in the Experts view to match the schema, a thing that happened in a drupal update hook, but did not happen in the profile anywhere yet.
=> Issue 922 expert sort

modules/wri_common/wri_common.module, modules/wri_data/config/install/field.field.node.data.field_narrative_taxonomy.yml, modules/wri_data/wri_data.install, modules/wri_narrative/wri_narrative.post_update.php, modules/wri_program/config/install/field.field.node.program_center.field_narrative_taxonomy.yml, modules/wri_project/config/install/field.field.node.project_detail.field_narrative_taxonomy.yml, modules/wri_project/wri_project.install, modules/wri_publication/config/install/field.field.node.publication.field_narrative_taxonomy.yml, modules/wri_publication/wri_publication.install, modules/wri_region/config/install/field.field.node.region.field_narrative_taxonomy.yml
- Creates a new token "link" which will display the text of a node or taxonomy term if it's unpublished, and the link to that entity if it's published
- Updates the default narrative taxonomy to use this new token instead of the cobbled-together /node/ or /taxonomy/term links.
- Provides an update hook for setting this new narrative taxonomy default.
- Provides a post-update hook for updating any existing database entries with this pattern in it to the new pattern.
=> Issue 1030 unpublished name

modules/wri_common/wri_common.module
- For https://github.com/wri/wriflagship/issues/1030#issuecomment-1559921745 adds some additional layers of fallback logic.
=> Issue #1030 more exciting fallback behavior for person links.

.circleci/config.yml, composer.json, modules/wri_listing_block/wri_listing_block.install
Just updating the distro_helper for https://github.com/thinkshout/distro_helper/pull/16 which revealed a bug.
=> Distro helper test

modules/wri_engagement/js/trigger-modal-body.js, modules/wri_engagement/templates/download-modal.html.twig, modules/wri_engagement/wri_engagement.libraries.yml, modules/wri_subpage/templates/wri-subpage-columns.html.twig, modules/wri_subpage/wri_subpage.layouts.yml, themes/custom/ts_wrin/sass/components/_publication-detail.scss, themes/custom/ts_wrin/sass/layout/_page.scss
- Adds a buttons region to the layout, and fixes the nav/header/subnav z-index problems a more specific way.
=> Issue 164 pub sub

modules/wri_node/templates/wri-page-hero.html.twig, modules/wri_node/wri_node.module, themes/custom/ts_wrin/templates/_includes/wri-page-hero--wri-paying-for-paris-wri-paying-for-paris.html.twig
This should fix the fact that layouts don't seem to allow theme suggestions.
=> Twig swapper header trickery.

composer.json, themes/custom/ts_wrin/sass/components/_search-archive.scss, themes/custom/ts_wrin/templates/views/views-view--paying-for-paris-resources.html.twig
=> Issue 1053

themes/custom/ts_wrin/templates/fields/field--block-content--field-accordion-items.html.twig, themes/custom/ts_wrin/templates/paragraphs/paragraph--accordion-item--default.html.twig
Issue: https://github.com/wri/wriflagship/issues/1051
**Reviewer**:
Styles and adds interaction for the rich accordion component. This PR does not style the WYSIWYG content inside the accordion drawer, only the accordion itself.
- Go to `/paying-paris-agreement/aligning-public-finance`
- Check styling and interaction
- Go to `/paying-paris-agreement/aligning-public-finance#section-public-investments-spending-incentives`
- You should be scrolled down to the accordion and it should auto expand.
https://github.com/wri/wriflagship/pull/1073
=> 1051 rich accordion

composer.json, modules/wri_homepage/wri_homepage.info.yml
Deleted onlyone module from /modules/wri_homepage/wri_homepage.info.yml file.
-
=> #158 deleted onlyone module

composer.json
Removed s3fs module to move to wriflagship project.
-
-
-
=> #159 removed s3sf from profile

composer.json
- Apply patch to search_api module
https://www.drupal.org/project/search_api/issues/3253738
-
-
=> #150 added patch for php8.1 search_api

modules/wri_image_cta/templates/wri-image-cta.html.twig, themes/custom/ts_wrin/sass/components/_image-cta-block.scss, themes/custom/ts_wrin/sass/components/_search-archive.scss, themes/custom/ts_wrin/sass/components/_search-results.scss, themes/custom/ts_wrin/templates/menus/menu--extras--microsites--content.html.twig, themes/custom/ts_wrin/templates/paragraphs/layout--onecol--paragraph--accordion-item.html.twig
Fixed a los of css issues and js
https://github.com/wri/wriflagship/issues/1100
-
-
-
=> Round 2 qa #1100

themes/custom/ts_wrin/sass/components/_search-results.scss
Removed line bottom on events for mobile.
-
-
-
=> #344 fixed underline on events

themes/custom/ts_wrin/sass/components/_project-detail.scss
- Added max width on logos in the sidebar.
-
-
=> #396 added max width on logos

modules/wri_external_resources/config/install/core.entity_form_display.node.external_resource.default.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.card.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.default.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.full.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.impact.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.large_image_teaser.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.main_content.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.search_results.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.small_image_teaser.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.superfeatured.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.teaser.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.tile.yml, modules/wri_external_resources/config/install/core.entity_view_display.node.external_resource.type_title.yml, modules/wri_external_resources/config/install/field.field.node.external_resource.field_intro.yml, modules/wri_external_resources/config/install/field.field.node.external_resource.field_main_image.yml, modules/wri_external_resources/config/install/field.field.node.external_resource.field_metatags.yml, modules/wri_external_resources/config/install/field.field.node.external_resource.field_primary_topic.yml, modules/wri_external_resources/config/install/field.field.node.external_resource.field_source.yml, modules/wri_external_resources/config/install/field.field.node.external_resource.field_type.yml, modules/wri_external_resources/config/install/field.field.node.external_resource.layout_builder__layout.yml, modules/wri_external_resources/config/install/field.storage.node.field_source.yml, modules/wri_external_resources/config/install/node.type.external_resource.yml, modules/wri_external_resources/wri_external_resources.info.yml, modules/wri_external_resources/wri_external_resources.module
- Adds the external resources content type
=> Adding an external resource module to the profile.

modules/wri_taxonomy/config/install/field.field.taxonomy_term.topics_and_subtopics.field_default_image.yml, modules/wri_taxonomy/config/install/field.storage.taxonomy_term.field_default_image.yml, modules/wri_taxonomy/wri_taxonomy.install
- updates install hook to work with fields
=> Field install fix

modules/wri_node/config/install/wri_node.settings.yml, modules/wri_node/config/schema/wri_node.schema.yml, modules/wri_node/src/Form/SettingsForm.php, modules/wri_node/wri_node.module, themes/custom/ts_wrin/templates/layout/html.html.twig
=> added Osano script

modules/wri_engagement/config/install/simple_popup_blocks.popup_beforefilesmodal.yml, modules/wri_engagement/config/install/views.view.node_downloads.yml, modules/wri_engagement/config/install/webform.webform.download_publication.yml, modules/wri_engagement/config/install/wri_engagement.settings.yml, modules/wri_engagement/config/schema/wri_engagement.schema.yml, modules/wri_engagement/wri_engagement.install, modules/wri_engagement/wri_engagement.libraries.yml, themes/custom/ts_wrin/sass/components/ui-dialog.scss
- Pulls over the config so IOs will not be messed up.
- Updates theming to look more like it did previously for download files buttons
- Adds some hidden fields to the download interrupter form.
=> Issue 301 96

composer.json, modules/wri_menus/src/Menu/WriMenuLinkTree.php, modules/wri_menus/src/Plugin/Block/ParentMenuBlock.php, modules/wri_menus/wri_menus.services.yml, themes/custom/ts_wrin/config/install/block.block.ts_wrin_main_menu.yml, themes/custom/ts_wrin/sass/global/_wysiwyg.scss, themes/custom/ts_wrin/ts_wrin.theme
- Fixing some bugs in the D10 release
=> Patch to fix events path.

modules/wri_menus/wri_menus.info.yml
- Adds Jquery Once as a requirement. This module was enabled by an update hook but was not added as an install requirement.
=> Requiring jquery once for the hamburger menu.

composer.json
=> Adds entity_usage to the profile

modules/wri_media/config/install/editor.editor.full_html.yml, modules/wri_media/wri_media.install, themes/custom/ts_wrin/README.md, themes/custom/ts_wrin/package-lock.json
- Adds the ability to add named empty link tags
=> Issue #1166 adding update hook for empty tags in full html.

composer.json
=> Issue #423 updating patch.

themes/custom/ts_wrin/templates/layout/html.html.twig
=> Issue #266 updating google consent.

modules/wri_admin/wri_admin.info.yml, modules/wri_program/config/install/core.entity_view_display.node.program_center.full.yml, modules/wri_program/config/install/field.field.node.program_center.field_twitter_account.yml, modules/wri_project/config/install/field.field.node.project_detail.field_twitter_account.yml, themes/custom/ts_wrin/sass/global/_wysiwyg.scss
- Adds the position: relative to the div surrounding images so captions can float to the right like they are supposed to.
-
-
=> Issue #287 fixing captions that were invisible.

modules/wri_admin/wri_admin.post_update.php, themes/custom/ts_wrin/sass/components/_article-detail.scss, themes/custom/ts_wrin/sass/config/_04.base.scss, themes/custom/ts_wrin/sass/global/_wysiwyg.scss
- Updates the css for san-serif pages 
- Adds an update hook for pages already using a class featured-content-list.
=> Issue 451 updates

modules/wri_search/config/install/views.view.search.yml, modules/wri_search/wri_search.install
- Sorts search results by date published, if all other sorts are equal.
-
-
=> Issue #923 update hook to add creeated_1 sort.

themes/custom/ts_wrin/js/components/ts_forms.js, themes/custom/ts_wrin/sass/config/_05.buttons.scss, themes/custom/ts_wrin/sass/config/_06.forms.scss
Webform forms design update.
- Issue Number: https://github.com/wri/WRIN/issues/453
More pretty.
[Empty Form](https://www.figma.com/proto/LZdIWVClbTpJWMD6lYX2fX/Event-Registration-Integration?page-id=16%3A1236&node-id=16-1238&viewport=475%2C453%2C1&t=ZycdiQiSKXy4IOO1-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=16%3A1238&show-proto-sidebar=1) |[ Filled-out Form](https://www.figma.com/proto/LZdIWVClbTpJWMD6lYX2fX/Event-Registration-Integration?page-id=16%3A1236&node-id=16-1385&viewport=475%2C453%2C1&t=ZycdiQiSKXy4IOO1-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=16%3A1385&show-proto-sidebar=1) | [All Errors](https://www.figma.com/proto/LZdIWVClbTpJWMD6lYX2fX/Event-Registration-Integration?page-id=16%3A1236&node-id=16-1743&viewport=475%2C453%2C1&t=Zy …
=> Wri 453  form fields

modules/wri_event/src/Plugin/DsField/CalendarEvent.php, modules/wri_media/config/install/editor.editor.full_html.yml, modules/wri_media/config/install/filter.format.full_html.yml, modules/wri_media/wri_media.install, themes/custom/ts_wrin/sass/ckeditor.scss, themes/custom/ts_wrin/sass/global/_wysiwyg.scss
Misc adjustments to the blockquote element.
- Less massive font
- Ability to see it in the WYSIWYG
- Optional initial quote
=> Wri 472 blockquote

modules/wri_event/wri_event.install, themes/custom/ts_wrin/sass/components/_events.scss
https://github.com/wri/WRIN/issues/473#issuecomment-2361971599 - fixes comma spacing issue.
Permanent comma-spacing fix.
=> #473: fix comma bug and remove asset injector

.ci/check-for-new-tag.sh, .ci/deploy.sh, .ci/util.sh
Script changes for faster deployments.
- New script check-for-new-tag.sh checks to see if there are new tags since the last release
- Removed references to vendor in util.sh
=> Faster IO Deployments

.ci/pre-deploy.sh
- adding efficiency to deployment process 
(https://github.com/wri/WRIN/issues/387)
- Updated pre-deploy.sh to complete Deploying steps from [WRI Deployment Checklist]( https://github.com/wri/WRIN/wiki/Deployment-Checklist)
=> Updating pre-deploy.sh

modules/wri_maps/src/Controller/MapsController.php
Add caching to custom json response on maps functionality
This adds caching to the json response from the maps functionality.
=> Update caching code on MapsController

composer.json
=> Added patch for issue 372

modules/wri_node/wri_node.module
- Disables osana on 403 and 404 pages.
=> Issue 518 osana

themes/custom/ts_wrin/templates/facets/facets-item-list--links--all-event-topics.html.twig, themes/custom/ts_wrin/templates/facets/facets-item-list--links--all-topics.html.twig, themes/custom/ts_wrin/templates/facets/facets-item-list--links--content-type.html.twig, themes/custom/ts_wrin/templates/facets/facets-item-list--links--experts-all-topics.html.twig
- Wraps facets in a div needed for a patch on Flagship.
=> Facet block test

modules/wri_spoke/src/Path/SpokeHostProcessor.php
#448 
Created as a hotfix to provide options.
=> HOTFIX: Check if URL is routed before asking for its route.

composer.json, modules/wri_spoke/wri_spoke.info.yml
- Enables ultimate cron for all sites.
=> Adding ultimate cron for all spoke sites.

modules/wri_spoke/config/install/entity_share_client.import_config.hub_events.yml, modules/wri_spoke/src/Plugin/EntityShareClient/Processor/DefaultRegistrationLink.php, modules/wri_spoke/wri_spoke.install
[#534](https://github.com/wri/WRIN/issues/534)
https://pr-1343-wriflagship.pantheonsite.io/ for QA -- as of posting I'm cloning a fresh database to this multidev which was behaving strangely.
=> Populate the registration field when blank on import. 

composer.json
- Moves to the latest release on d.o.
=> Using distro helper on d.o.
