wri/wri_sites

- modules/wri_subpage/wri_subpage.module
On Flagship, the first time you add a subpage to a project or program, it adds that information to the url. If you update the subpage, it drops the parent path in the url.
- Removes the default value of ":" for the menu parent setting on subpages. I have no idea why that's there!
> Subpage multiple-save issue fix.

- modules/wri_search/config/install/facets.facet.all_event_topics.yml
- modules/wri_search/config/install/facets.facet.all_topics.yml
- modules/wri_search/config/install/facets.facet.experts_all_topics.yml
- modules/wri_search/config/install/search_api.index.sitewide.yml
- modules/wri_search/src/Plugin/Field/FieldType/WriSmartTopic.php
- modules/wri_search/wri_search.install
- modules/wri_search/wri_search.module
Jira ticket wri-1307 -- see https://docs.google.com/document/d/1hhnpdMrO5kOG0_p1h6YzuNVZIt7q9p_8BxyBy-SjC9k/edit#
The facets on the top of the resource library are only pulling in the "field_primary_topic" which means that when a user is filtering using the facet, they are missing a lot of content where that topic is added a secondary tag. 
You can see the difference here:Facet filter (leading topic business) here: https://www.wri.org/resources/topic/business-74/type/research-65
All things tagged business here: https://www.wri.org/resources/type/research-65/tags/business-74 
Facet settings are controlled here: wri.org/admin/config/search/facets .
Ideally we would only want …
> Topic filter fix

- modules/wri_seo/wri_seo.module
Fix for https://github.com/wri/WRIN/issues/323
Multidev PR: https://github.com/wri/WRIN/issues/323
Issue Number: 323
- "Every project page has two associated pages: the experts page and the project resources page. These are throwing a lot of issues in our SEM audit as they all have the same title tags and meta-descriptions and they also have a funny url pattern --> aka not nested under the project they are associated with."
- Adds `<meta name="robots" content="noindex, nofollow">` to pages that have `/project-resources/` or `/project-experts/` in their paths.
> #323: add noindex, nofollow to project pages

- wri_sites.install
https://github.com/wri/WRIN/issues/296
~~~
Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.
Custom block
The block_content.field_hero_type field needs to be updated.
Content
The node.field_toc field needs to be updated.
Paragraph
The paragraph.field_hero_image field needs to be updated.
The paragraph.field_hero_intro field needs to be updated.
The paragraph.field_hero_title field needs to be updated.
~~~
Issue Number: https://github.com/wri/WRIN/issues/296
- No errors!
> #296: update hook to clear field definition errs

- modules/wri_services_reader/src/Plugin/rest/resource/WriReaderRetrieveNodeResource.php
Fixes an error because files don't have a canonical url in Drupal, and the `url` method is deprecated in D9.
- Updates the url call based on the advice here: https://drupal.stackexchange.com/a/308999
> Issue #362 updating how the file gets called.

- modules/wri_topics/components/wri_topics_block.sfc
- Adds functionality to hide the centers view from display on the WRI topics block
> Updates topics block to make centers display an option - #62

- themes/custom/ts_wrin/sass/global/_header.scss
- Header submenus no longer have text capitalized by default
> #69: remove capitalization on submenus

- themes/custom/ts_wrin/sass/global/_footer.scss
- themes/custom/ts_wrin/templates/layout/page.html.twig
- themes/custom/ts_wrin/ts_wrin.theme
- Footer logo does not match site logo
- Footer logo uses 'logo white' style
> 65 footer logo

- themes/custom/ts_wrin/sass/global/_footer.scss
- Secondary Footer does not flex to allow for fewer than three columns.
- Secondary menu accommodates 1 - 3 columns gracefully. 
> #357: let secondary footer menu items to flex-grow

- modules/wri_seo/js/wri_seo.js
- modules/wri_seo/wri_seo.module
- Adds primary topic to the datalayer for all content types for access via GTM.
> Adds primary topic to dataLayer - #786

- modules/wri_taxonomy/wri_taxonomy.module
- Currently tags on the Brasil site link to `/resources` but that page is called `recursos` on that site. That url needs to be configurable based on the url of the view it points to.
> Issue 89 resources

- themes/custom/ts_wrin/sass/components/_homepage.scss
- themes/custom/ts_wrin/sass/global/_header.scss
items identified by [Pagespeed Insights](https://pagespeed.web.dev/) that have layout shift (CLS)
- No layout shift
> #374: fix layout shift issues

- composer.json
- modules/wri_media/config/install/core.entity_view_display.media.video.default.yml
- modules/wri_media/wri_media.info.yml
- modules/wri_media/wri_media.install
Adds Lazy Loading to oembed media to improve performance
- Embedded videos below the fold do not load (or call the large YouTube libraries) until they are close to the viewport. 
> #371: add oembed_lazyload, configure media->video.

- modules/wri_subpage/wri_subpage.module
- themes/custom/ts_wrin/templates/layout/page--microsite.html.twig
- themes/custom/ts_wrin/ts_wrin.theme
Issue Number: https://github.com/wri/wriflagship/issues/768
- Updates .theme to allow for a custom page template for the 'Microsite' content type.
- Adds a stripped-down `page--microsite.html.twig` template for the above.
- Ensures subpages of microsites inherit the `page--microsite.html.twig`.
- Adds parent & child microsite pages to the microsites menu.
> #768: microsite subpage tweak, page templates.

- modules/wri_node/layouts/layout--card.html.twig
- modules/wri_node/src/Form/SettingsForm.php
- modules/wri_node/wri_node.links.menu.yml
- modules/wri_node/wri_node.module
- modules/wri_node/wri_node.routing.yml
- themes/custom/ts_wrin/ts_wrin.theme
Reworks the default image behavior to use a fallback if the topic is not found.
- moves it to a preprocess function to create a new variable
- Fixes a bug in the microsites logic.
> Add default cards image 902

- modules/wri_block/src/Plugin/Block/RelatedResourcesFallback.php
- modules/wri_block/src/Plugin/Field/FieldFormatter/RelatedFieldFormatter.php
- Adds a 60 second cache to the block rendering if it's empty. Prevents a cached empty block from showing forever.
> Issue 932 cache

- modules/wri_person/config/install/core.entity_form_display.block_content.person_listing.default.yml
- modules/wri_person/config/install/core.entity_view_display.block_content.person_listing.default.yml
- modules/wri_person/config/install/field.field.block_content.person_listing.field_more_link.yml
- modules/wri_person/wri_person.install
- modules/wri_publication/config/install/views.view.other_publications_in_this_series.yml
- themes/custom/ts_wrin/templates/fields/field--block-content--field-featured-experts.html.twig
- themes/custom/ts_wrin/templates/fields/field--node--field-featured-experts.html.twig
- themes/custom/ts_wrin/ts_wrin.theme
- Updates the person_listing  field to allow editors  to add a custom link
> Microsites experts

- modules/wri_article/config/install/core.entity_form_display.node.article.default.yml
- modules/wri_common/wri_common.install
- modules/wri_data/config/install/core.entity_form_display.node.data.default.yml
- modules/wri_engagement/config/install/core.entity_form_display.block_content.modal.default.yml
- modules/wri_event/config/install/core.entity_form_display.node.event.default.yml
- modules/wri_homepage/config/install/core.entity_form_display.paragraph.homepage_hero.default.yml
- modules/wri_image_cta/config/install/core.entity_form_display.block_content.image_cta.default.yml
- modules/wri_io_content/config/install/core.entity_form_display.node.international_office.default.yml
- modules/wri_large_cta/config/install/core.entity_form_display.block_content.large_cta.default.yml
- modules/wri_page/config/install/core.entity_form_display.node.page.default.yml
- modules/wri_person/config/install/core.entity_form_display.node.person.default.yml
- modules/wri_program/config/install/core.entity_form_display.node.program_center.default.yml
- modules/wri_project/config/install/core.entity_form_display.node.project_detail.default.yml
- modules/wri_project/config/install/core.entity_form_display.paragraph.partner_logo.default.yml
- modules/wri_project/config/install/views.view.featured_experts.yml
- modules/wri_publication/config/install/core.entity_form_display.node.publication.default.yml
- modules/wri_region/config/install/core.entity_form_display.node.region.default.yml
- modules/wri_region/config/install/core.entity_form_display.taxonomy_term.regions.default.yml
- modules/wri_simple_page/config/install/core.entity_form_display.node.simple_page.default.yml
- modules/wri_simple_page/config/install/core.entity_form_display.paragraph.image.default.yml
- modules/wri_subpage/config/install/core.entity_form_display.node.subpage.default.yml
- modules/wri_unique_feature/config/install/core.entity_form_display.block_content.unique_feature_cta.default.yml
- Updates all fields that use the media library widget to also show  the edit button within the profile's config
- Provides an update hook to do the same on all existing fields.
> Issue 383 pdf overwrite

- themes/custom/ts_wrin/sass/components/_homepage.scss
- themes/custom/ts_wrin/sass/components/_person.scss
- themes/custom/ts_wrin/sass/components/_publication-detail.scss
- themes/custom/ts_wrin/sass/components/_search-results.scss
- themes/custom/ts_wrin/sass/config/_04.base.scss
- Adding back image settings that were needed when blazy existed to fix XLarge screens.
> Issue #398 adding all the blazy properties to all images.

- modules/wri_author/src/Commands/WriAuthorCustomCommands.php
- modules/wri_author/wri_author.module
- Adds a new drush command to clean up internal authors that may be pointing to deleted author nodes.
- Also removes a reference to (WRI) which I took out once we could use the advanced  autocomplete to distinguish between internal and external authors.
> Issue #212 a command to clean up internal authors and can run first.

- modules/wri_node/wri_node.module
Added a new functionality to get image from taxonomy term if not continue with the current behavior to get default image by name or by a default image if there is not a taxonomy term.
-
-
-
> #809 Added default image on taxonomy

- themes/custom/ts_wrin/sass/config/_06.forms.scss
- [x ] Issue Number: #WRIN/1109
Fixed issue on textarea on forms, adding padding to avoid words in bad position affecting the label.
> #1109 added padding for textarea

- modules/wri_subpage/wri_subpage.module
We had a fix for this in place before, but the issue has come back where when you save a subpage, it automatically gets re-added to its respective project page menu. 
Added a fix and added conditions for change value on page parent to generate auto menu link
> #403 added fix on subpages parent page menu link

- themes/custom/ts_wrin/sass/config/_05.buttons.scss
- themes/custom/ts_wrin/templates/fields/field--reset--node--field-source--external-resource.html.twig
Added style and structure for resource external link field.
-
-
-
> #117 added source external link style

- themes/custom/ts_wrin/sass/global/_header.scss
Adjust breakpoint at which the man nav hides
Both header navs should hide at 1200px viewport.
> adjust breakpoint that main menu is hidden #288

- modules/wri_subpage/wri_subpage.module
This reverts commit dcb1624d6d1751b6ca78640f7e174dfc0a0d335c, reversing changes made to 9f71518d00d4152400447bf5340e81bafb045d9a.
- Undoes what turned out to be an overly-heavy correction to the update behavior, and updates the edit form to merely suggest what the parent menu item should be, if a parent item is set.
> Revert "Merge pull request #204 from wri/403-subpages-subnav"

- modules/wri_subpage/wri_subpage.module
- Takes a new approach to menu creation -- only on create, not update, done through a form alter instead of through a presave.
> Issue 403 menu again

- themes/custom/ts_wrin/js/components/ts_header_nav.js
- themes/custom/ts_wrin/sass/components/_popup_modal.scss
- themes/custom/ts_wrin/templates/layout/page.html.twig
- themes/custom/ts_wrin/ts_wrin.info.yml
> Issue 293 example

- modules/wri_engagement/config/install/views.view.node_downloads.yml
- modules/wri_engagement/wri_engagement.module
- Fixes subpages to use the parent's node id, avoiding duplicates on translations
- Allows you to pass a translation value to the view: `/node/815/download` and `/en/node/815/download`
> 301 translations

- composer.json
- Builds started failing when we upgraded to 10.3.0, so locking to 10.2.x until https://github.com/wri/wri_sites/issues/278 is done
> Locking core to 10.2.x so we don't have to update patches.

- modules/wri_search/config/install/search_api.index.sitewide.yml
- modules/wri_search/wri_search.install
- Disables the highlighting processor, which we don't use.
> Issue 150 disable highlight

- composer.json
- modules/wri_admin/css/admin.css
- modules/wri_admin/templates/ckeditor5_template.json
- modules/wri_media/config/install/core.entity_view_display.media.image.thumbnail.yml
- modules/wri_media/config/install/core.entity_view_mode.media.thumbnail.yml
- modules/wri_media/config/install/filter.format.full_html.yml
- modules/wri_media/config/install/image.style.180x240_scale.yml
- modules/wri_media/wri_media.info.yml
- modules/wri_media/wri_media.install
- themes/custom/ts_wrin/sass/ckeditor.scss
- themes/custom/ts_wrin/sass/components/_programs.scss
- themes/custom/ts_wrin/sass/config/_04.base.scss
- themes/custom/ts_wrin/sass/global/_wysiwyg.scss
Adds a CKEditor template for 'Report Teaser', with optional thumbnail image in a new 180x240 image size.
- Version bump to responsive_tables_filter (was preventing the full_html text format from saving)
- adds 180x240_scale image style
- updated the 'thumbnail' media display mode to use the new image style
- Adds a CKEditor template: 'Report Teaser' with appropriate styling in both WYSIWYG and site display
> WRI #452 Report/publication teaser

- modules/wri_publication/templates/wri-publication-columns.html.twig
- modules/wri_subpage/templates/wri-subpage-columns.html.twig
- themes/custom/ts_wrin/js/components/ts_header_nav.js
- themes/custom/ts_wrin/sass/components/_simple-page.scss
- themes/custom/ts_wrin/sass/components/_toc.scss
- themes/custom/ts_wrin/templates/fields/field--reset--child-pages.html.twig
Replace black bar submenus on mobile for project pages, tweak simple-page mobile dropdown location.
- Subpage menus on /aqueduct and /toolbox/setting-enterprise-water-targets are a dropdown on screen sizes under 48 rems.
- The menu dropdown appears above the "About us" title on /about on mobile, and continues to be a dropdown until we hit 48rems screen size.
> Wri 462  submenu

- modules/wri_event/layouts/layout--event.html.twig
Webforms show for events that are passed. 
Auto-Hides event forms after events.
> #471: hide form after event.

- modules/wri_external_pub/src/Plugin/Block/ExternalPubBlock.php
- themes/custom/ts_wrin/sass/components/_publication-detail.scss
- themes/custom/ts_wrin/sass/components/report-teaser-overrides.scss
- themes/custom/ts_wrin/sass/global/_wysiwyg.scss
- themes/custom/ts_wrin/sass/style.scss
Misc layout and formatting bugs for the Research/Publication Highlight template.
- Fixed wide column issue
- fixed Z-index
- fixed publication / report WYSIWYG hover behavior
> #452: pub/teaser layout bugs

- modules/wri_zoom/config/install/webform.webform.zoom_default.yml
- modules/wri_zoom/src/Plugin/WebFormElement/IPAddress.php
- modules/wri_zoom/wri_zoom.install
Adding a custom IP Address WebformElement to get the correct client IP address on Pantheon. 
- Updated IP Address element that checks proxy headers and `remote_addr`.
- Update hook to apply to existing webforms.
> #314: Add new IP Address element, update hook.

- modules/wri_admin/templates/ckeditor5_template.json
- themes/custom/ts_wrin/sass/ckeditor.scss
Adds CKEditor template for the podcast 'Listen On' icons. 
Icons! Add links in CKEditor. 
> #302: 'Listen on' CKEditor template for podcasts

- modules/wri_admin/config/install/content_snippets.items.yml
- modules/wri_common/js/wri_gtm.js
- modules/wri_common/wri_common.install
- modules/wri_common/wri_common.module
- modules/wri_listing_block/config/install/content_snippets.content.yml
- themes/custom/ts_wrin/templates/layout/html.html.twig
- Configures the googletagmanager url via content snippets.
> Issue 323 gtm

- themes/custom/ts_wrin/js/components/wri_cta_banners.js
- themes/custom/ts_wrin/js/main.js
- themes/custom/ts_wrin/sass/components/_popup_modal.scss
- themes/custom/ts_wrin/templates/blocks/block--bundle--modal.html.twig
Adds a CTA banner 'close' icon and JS to manage display of the banners in a random manner.
> Wri 487 donate

- modules/wri_event/config/install/asset_injector.css.address_honeypot_field.yml
- modules/wri_event/config/install/smart_date.smart_date_format.compact_dot.yml
- modules/wri_event/wri_event.install
- themes/custom/ts_wrin/js/components/wri_datetime.js
- themes/custom/ts_wrin/js/main.js
- themes/custom/ts_wrin/sass/components/_events.scss
- Reformats to GMT offset the prepend 'GMT' when there's a value
- Updates / removes asset injectors as needed
Issue: https://github.com/wri/wriflagship/issues/1245
Moves the fix from asset injector(s) to config/code.
> Flagship issue #1245: hardcode GMT in date / times

- modules/wri_homepage/config/install/core.entity_view_display.paragraph.featured_statement.preview.yml
- modules/wri_homepage/wri_homepage.install
Can't see the edit button for the Featured Preview paragraph b/c the string is too long. 
- Issue Number: https://github.com/wri/wri-espanol/issues/27
Adds a preview mode to the 'Featured Paragraph' so the link field can be trimmed in admin.
> WRI-Espanol Issue  #27 - trim length of link

- modules/wri_media/config/install/editor.editor.full_html.yml
- modules/wri_media/config/install/filter.format.full_html.yml
- modules/wri_media/wri_media.install
- themes/custom/ts_wrin/sass/ckeditor.scss
- themes/custom/ts_wrin/sass/global/_wysiwyg.scss
More fine-tuning of the blockquote.
- Issue Number: https://github.com/wri/WRIN/issues/472
- Double quote instead of single, in Caslon Pro (serif)
- Attribution property (another style)
> #472: more double-quote adjustments

- themes/custom/ts_wrin/js/components/ts_external_links.js
- themes/custom/ts_wrin/js/components/ts_header_nav.js
- themes/custom/ts_wrin/sass/components/_simple-page.scss
- themes/custom/ts_wrin/sass/components/_toc.scss
- Submenus are not sticky, and external links should indicate so. 
- Sticky subnavs for mobile
- External site / project indicators
> Wri 475 submenu r2

- composer.json
- modules/wri_maps/src/Plugin/Block/RegionMapBlock.php
- modules/wri_maps/templates/wri-region-map.html.twig
- themes/custom/ts_wrin/js/components/wri_maps.js
- themes/custom/ts_wrin/sass/components/_region-map.scss
- https://github.com/wri/wri_sites/issues/305
> #305: Hide giant SVG map for mobile.

- modules/wri_narrative/wri_narrative.module
Fixes site error when the 'cities' filter is applied.
- `field_landing_page` might not exist on $term
- `->entity` might be null if `field_landing_page` is empty or not referencing a valid entity
- `field_narrative_taxonomy` might not exist on the entity referenced by `field_landing_page`. 
Added a set of checks for all possibilities and it's working as expected. 
> Fix for WSOD - check intermediate objects, etc.

- composer.json
- Individual metatags can now be added to views
> PR - Allow metatags to show up in views

- themes/custom/ts_wrin/sass/global/_header.scss
Positions header relatively instead of absolutely when in print mode.
- Changes header css to position: relative when in print mode
> Update header to fix print issue

- modules/wri_common/theme/wri-common-social-sharing-block.html.twig
- Adds Bluesky share link and rearranges the order to move X down.
> Bluesky 513

- modules/wri_custom_page/config/install/node.type.custom_page.yml
- modules/wri_custom_page/wri_custom_page.install
- modules/wri_menus/src/Plugin/Block/ParentMenuBlock.php
- modules/wri_menus/src/Plugin/Derivative/MenuBlock.php
- modules/wri_toc/config/schema/wri_toc.schema.yml
- modules/wri_toc/src/Plugin/Block/HorizontalBarMenuBlock.php
- modules/wri_toc/src/Plugin/Field/FieldFormatter/TableofcontentsFormatter.php
- modules/wri_toc/src/Traits/TocConfigTrait.php
- themes/custom/ts_wrin/sass/components/_simple-page.scss
- themes/custom/ts_wrin/templates/blocks/block--parent-menu-block--page-hierarchies.html.twig
- Adds a 'WRI' page hierarchy menu
- Makes it available as a horizontal menu
> WRIN #518: Add HorizontalBarMenuBlock.php

- composer.json
The diff changed because the PR has changed, and no longer applies to the latest release. Patch recently added to the issue itself appears to be the same as the diff used to be.
Pantheon complains about failed patches, so this is needed for #389
> Update layout_builder_st patch.

- modules/wri_admin/config/install/content_snippets.items.yml
- modules/wri_event/wri_event.install
- modules/wri_listing_block/config/install/content_snippets.content.yml
- modules/wri_zoom/src/Form/AdminSettingsForm.php
- modules/wri_zoom/wri_zoom.links.menu.yml
- modules/wri_zoom/wri_zoom.module
- modules/wri_zoom/wri_zoom.post_update.php
- modules/wri_zoom/wri_zoom.routing.yml
#393
flaship PR for qa: https://github.com/wri/wriflagship/pull/1318
Sets aside ORTO integration settings (and Zoom, but there aren't any to really set that I noticed) and adds an "enabled" setting which can be easily overridden in settings.php to insulate against ORTO running in dev environments.
> Create admin form and settings override capability for orto integration

- modules/wri_custom_page/config/install/core.entity_view_display.node.custom_page.full.yml
- modules/wri_custom_page/wri_custom_page.install
Limits custom layouts available to Custom Page
- Update hook for custom_page full display mode.
> Wri 380  limit layouts

- composer.json
- modules/wri_article/wri_article.module
Two updates to Schema.org metatags. 
- description under 'person'
- maxlength increase for org/author
> Wri 371  metatags

- themes/custom/ts_wrin/config/install/ts_wrin.settings.yml
- themes/custom/ts_wrin/templates/blocks/block--ts-wrin-branding.html.twig
- themes/custom/ts_wrin/templates/layout/page.html.twig
- themes/custom/ts_wrin/templates/layout/region--hamburger-nav.html.twig
- themes/custom/ts_wrin/templates/ts_custom/maintenance-page.html.twig
- themes/custom/ts_wrin/theme-settings.php
- themes/custom/ts_wrin/ts_wrin.theme
We need to link the logo on the hub site back to wri.org.
- Allows you to overwrite the default "logo goes to the homepage" with a custom url
- Takes care of the header logo, as well as the ones in the footer, on the maintenance page, and in the hamburger menu (if that's enabled)
- You can overwrite the setting on the theme page at `admin/appearance/settings/ts_wrin`
> Logo hardcode

- themes/custom/ts_wrin/js/components/ts_external_links.js
Site logo from https://hub.wri.org/ to https://wri.org/ opens in new tab
- excludes links with `site-logo`
> WRIF 499: skip site-logos

- modules/wri_spoke/src/Path/SpokeHostProcessor.php
- modules/wri_spoke/wri_spoke.services.yml
Address https://github.com/wri/WRIN/issues/535 -- changes backlinks from events to use "/events" when originating from an admin page.
@maria-thinkshout do you think this addresses the concern properly? Also, should we make that string configurable? I don't like hard-coding "/events" this way. Easy enough to convert to a snippet -- or we could get fancy and have an "events page indicator" field or something on nodes.
> Backlink to '/events' when visiting from an admin page.

- modules/wri_spoke/src/Form/EntityShareCronSettingsForm.php
- modules/wri_spoke/wri_spoke.module
You have to have separate channels for different languages.
This adds all the language option machine names that will need to be manually created on the hub with matching machine names. It also allows for multiple channels to be synced via cron.
#536
> Allow for cron pull from multiple channels.
